GLASSWARE_OPTIONS = [
  ["Aperitif Glass", "Aperitif Glass"],
  ["Beer Mug", "Beer Mug"],
  ["Beer Pilsner", "Beer Pilsner"],
  ["Bottle", "Bottle"],
  ["Brandy Snifter", "Brandy Snifter"],
  ["Champagne Flute", "Champagne Flute"],
  ["Champagne Saucer", "Champagne Saucer"],
  ["Champagne Tulip", "Champagne Tulip"],
  ["Cocktail Glass", "Cocktail Glass"],
  ["Coffee Mug", "Coffee Mug"],
  ["Collins Glass", "Collins Glass"],
  ["Cordial Glass", "Cordial Glass"],
  ["Coupe glass", "Coupe glass"],
  ["Cup", "Cup"],
  ["Highball Glass", "Highball Glass"],
  ["Hurricane Glass", "Hurricane Glass"],
  ["Irish Coffee Cup", "Irish Coffee Cup"],
  ["Jug", "Jug"],
  ["Margarita Glass", "Margarita Glass"],
  ["Mason Jar", "Mason Jar"],
  ["Mug", "Mug"],
  ["Old-Fashioned Glass", "Old-Fashioned Glass"],
  ["Parfait Glass", "Parfait Glass"],
  ["Pina Colada Glass", "Pina Colada Glass"],
  ["Pitcher", "Pitcher"],
  ["Pousse Cafe Glass", "Pousse Cafe Glass"],
  ["Punch Bowl", "Punch Bowl"],
  ["Red Wine Glass", "Red Wine Glass"],
  ["Sherry Glass", "Sherry Glass"],
  ["Shot Glass", "Shot Glass"],
  ["Sour Glass", "Sour Glass"],
  ["Test tube", "Test tube"],
  ["White Wine Glass", "White Wine Glass"],
  ["Wine Goblet", "Wine Goblet"]
]